### PR TITLE
Impl sub, mul and div for actual objects

### PR DESCRIPTION
**Pull request by Cesar199999**
Should solve the reference hell in https://github.com/HungryCatsStudio/aurora/blob/core/src/aurora/mod.rs#L288

### CODE REVIEW

**Comment by Antonio95** [comment]
Very sorely needed, thanks. Maybe there's a reason why it wasn't implemented in Arkworks (maybe Marcin nows about it; avoiding cloning?), but the syntax it requires is a nightmare

**Comment by Pratyush** [comment]
I think adding the APIs makes sense; I just hadn't added it because these versions move the input polynomials, so the caller will have to do `a.clone() - b.clone()` (for example).

**Comment by Cesar199999** [comment]
I'd say adding pass-by-value arithmetic shouldn't be too problematic since (1) it's already there for polynomial sum and (2) the user can still use the reference analogues if he doesn't want to consume the objects.

**Comment by mmagician** [comment]
@Cesar199999 probably worth adding upstream directly, then

**Review by Antonio95 — APPROVED** [review]
Very cool! Not cloning or moving data.

**Comment by Cesar199999** [comment]
> @Cesar199999 probably worth adding upstream directly, then

Sure, https://github.com/arkworks-rs/algebra/pull/843

**Pull request merged**
